# -*- coding: utf-8 -*-
"""BlackHolesim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXxM5xqcy9cQXi4CLRRBzKiolOULhNCf
"""

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, widgets
from IPython.display import display, clear_output

# Natural / SI Constants
G = 6.67430e-11        # m^3 kg^-1 s^-2
hbar = 1.0545718e-34   # J s
c = 299792458          # m/s
kB = 1.380649e-23      # J/K
yr_to_sec = 3.154e7    # Seconds in a year
age_universe = 13.8e9  # 13.8 billion years

def run_pbh_laboratory(log_initial_mass):
    clear_output(wait=True)

    # 1. Base Variables from Input (Mass in Grams translated to KG)
    M_init_g = 10**log_initial_mass
    M_init_kg = M_init_g / 1000.0

    # 2. Complete Evaporation Lifespan (Standard Semi-Classical Hawking Limit)
    # t_evap = (5120 * pi * G^2 * M^3) / (hbar * c^4)
    t_evap_sec = (5120 * np.pi * (G**2) * (M_init_kg**3)) / (hbar * (c**4))
    t_evap_yr = t_evap_sec / yr_to_sec

    # 3. Microscopic Horizon Metrics at Initial State
    r_sch_init = (2 * G * M_init_kg) / (c**2)  # Meters
    temp_init = (hbar * (c**3)) / (8 * np.pi * G * M_init_kg * kB)  # Kelvin

    # 4. Generate Dynamic Evaporation Profile Over Its Lifetime (Dynamic Evolution Array)
    # Mass decays as M(t) = M_init * (1 - t/t_evap)^(1/3)
    time_steps = np.linspace(0, t_evap_sec, 300)
    mass_evolution_kg = M_init_kg * (1 - time_steps / t_evap_sec)**(1/3)

    # Prevent divide by zero error at the absolute tip of evaporation
    mass_evolution_kg = np.clip(mass_evolution_kg, 1e-5, None)

    # Derive changing temperature and radius arrays across its life
    radius_evolution_m = (2 * G * mass_evolution_kg) / (c**2)
    temp_evolution_K = (hbar * (c**3)) / (8 * np.pi * G * mass_evolution_kg * kB)
    luminosity_evolution_W = (hbar * (c**6)) / (15360 * np.pi * (G**2) * (mass_evolution_kg**2))

    # Evaluate Stability Status
    if t_evap_yr >= age_universe:
        status_banner = "🟢 STABLE COLD DARK MATTER REMNANT"
        status_desc = f"Survives today. Lifespan exceeds the age of the universe by {t_evap_yr/age_universe:.2e}x."
    else:
        status_banner = "💥 EXPLODED / EVAPORATED RELIC"
        status_desc = f"Destroyed {age_universe - t_evap_yr:.2e} years ago. Released high-energy gamma-ray background radiation."

    # --- Render Graphical Dashboard Panel ---
    plt.style.use('dark_background')
    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 9))

    # Plot A: The Event Horizon & Quantum Temperature Grid
    # Graphic shifts size and color based on current inputs
    circle = plt.Circle((0, 0), radius=max(0.1, (log_initial_mass-13.5)/3), color='black', ec='blueviolet', lw=3.5)
    ax1.add_patch(circle)
    # Visual thermal emission flare (Inversely proportional to mass)
    glow_size = max(50, 1000 * (17 - log_initial_mass))
    ax1.scatter(0, 0, s=glow_size*2, color='darkorange', alpha=0.15)
    ax1.scatter(0, 0, s=glow_size, color='crimson', alpha=0.25)
    ax1.set_xlim(-1.5, 1.5)
    ax1.set_ylim(-1.5, 1.5)
    ax1.set_aspect('equal')
    ax1.axis('off')
    ax1.set_title("Physical Event Horizon Geometry", fontsize=11, fontweight='bold', color='violet')

    # Plot B: Mass Decay Over Lifetime
    ax2.plot(time_steps / yr_to_sec, mass_evolution_kg * 1000, color='cyan', lw=2)
    ax2.set_title("Mass Attrition Curve (Grams vs Time)", fontsize=11, fontweight='bold')
    ax2.set_xlabel("Time Elapsed (Years)")
    ax2.set_ylabel("Remaining Mass (g)")
    ax2.grid(True, linestyle='--', alpha=0.2)

    # Plot C: Thermal Runaway Curve (Hawking Temperature Spiking)
    ax3.plot(time_steps / yr_to_sec, temp_evolution_K, color='orangered', lw=2)
    ax3.set_yscale('log')
    ax3.set_title("Hawking Temperature Runaway Profile", fontsize=11, fontweight='bold')
    ax3.set_xlabel("Time Elapsed (Years)")
    ax3.set_ylabel("Temperature (Kelvin)")
    ax3.grid(True, linestyle='--', alpha=0.2)

    # Plot D: Cosmic Lifespan Constraint Boundary
    ax4.bar(["Total PBH Lifespan", "Age of Universe"], [t_evap_yr, age_universe], color=['darkmagenta', 'teal'], alpha=0.85)
    ax4.set_yscale('log')
    ax4.set_title("Temporal Cosmological Horizon Match", fontsize=11, fontweight='bold')
    ax4.set_ylabel("Duration Scale (Years)")
    ax4.grid(True, which="both", linestyle='--', alpha=0.2)

    # Print Formatted Analytical Readout
    print("=" * 80)
    print(f"🔬 PRIMORDIAL BLACK HOLE QUANTUM DYNAMICS CORE LABORATORY")
    print("=" * 80)
    print(f"• Initial Input Mass   : 10^{log_initial_mass:.2f} grams ({M_init_g:.2e} g)")
    print(f"• Event Horizon Radius : {r_sch_init:.2e} meters (Attometer/Sub-atomic scale)")
    print(f"• Horizon Temperature  : {temp_init:.2e} Kelvin")
    print(f"• Calculated Lifespan  : {t_evap_yr:.2e} Years")
    print(f"• Cosmological Status  : {status_banner}")
    print(f"  [{status_desc}]")
    print("=" * 80)

    plt.tight_layout()
    plt.show()

# Deploy Reactive Slider Metrics
print("Adjust the logarithmic slider to scale initial PBH formation mass:")
interact(run_pbh_laboratory, log_initial_mass=widgets.FloatSlider(
    value=15.0, min=14.0, max=16.5, step=0.05,
    description='Initial Mass Log10(g):', continuous_update=True));

with open("app.py", "w") as f:
    f.write('''
import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

st.set_page_config(page_title="PBH Lab Dashboard", layout="wide")
st.title("🌌 Primordial Black Hole Hawking Evaporation Laboratory")
st.write("An interactive quantum-thermodynamic simulator parsing Schwarzschild decay structures across cosmological eras.")

G = 6.67430e-11
hbar = 1.0545718e-34
c = 299792458
kB = 1.380649e-23
yr_to_sec = 3.154e7
age_universe = 13.8e9

col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("🎛️ Physical Controls")
    log_initial_mass = st.slider("Initial Formation Mass Log10(grams):", min_value=14.0, max_value=16.5, value=15.0, step=0.05)

    M_init_g = 10**log_initial_mass
    M_init_kg = M_init_g / 1000.0
    t_evap_sec = (5120 * np.pi * (G**2) * (M_init_kg**3)) / (hbar * (c**4))
    t_evap_yr = t_evap_sec / yr_to_sec
    r_sch_init = (2 * G * M_init_kg) / (c**2)
    temp_init = (hbar * (c**3)) / (8 * np.pi * G * M_init_kg * kB)

    if t_evap_yr >= age_universe:
        st.success(f"🟢 STABLE RELIC\\n\\nSurvives for {t_evap_yr:.2e} years. Viable Cold Dark Matter candidate.")
    else:
        st.error(f"💥 EVAPORATED CONSTRAINT\\n\\nDissolved {age_universe - t_evap_yr:.2e} years ago into diffuse gamma rays.")

    st.metric("Initial Horizon Radius", f"{r_sch_init:.2e} meters")
    st.metric("Initial Hawking Temperature", f"{temp_init:.2e} Kelvin")
    st.metric("Total System Lifespan", f"{t_evap_yr:.2e} Years")

with col2:
    st.subheader("📊 Dynamic Analytical Charts")
    time_steps = np.linspace(0, t_evap_sec, 200)
    mass_evolution_kg = M_init_kg * (1 - time_steps / t_evap_sec)**(1/3)
    mass_evolution_kg = np.clip(mass_evolution_kg, 1e-5, None)
    temp_evolution_K = (hbar * (c**3)) / (8 * np.pi * G * mass_evolution_kg * kB)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4.5))
    plt.style.use('dark_background')

    ax1.plot(time_steps / yr_to_sec, mass_evolution_kg * 1000, color='cyan', lw=2)
    ax1.set_title("Mass Decay Profile")
    ax1.set_xlabel("Time (Years)")
    ax1.set_ylabel("Mass (grams)")
    ax1.grid(True, linestyle='--', alpha=0.2)

    ax2.plot(time_steps / yr_to_sec, temp_evolution_K, color='orangered', lw=2)
    ax2.set_yscale('log')
    ax2.set_title("Hawking Thermal Runaway Loop")
    ax2.set_xlabel("Time (Years)")
    ax2.set_ylabel("Temperature (Kelvin)")
    ax2.grid(True, linestyle='--', alpha=0.2)

    st.pyplot(fig)
''')
print("Streamlit code successfully exported to app.py!")
